// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'collapse-all'
  | 'expand-all'
  | 'export-selected'
  | 'new-folder'
  | 'pref-include-subfolders'
  | 'pref-include-ungrouped'
  | 'pref-navigate-on-click'
  | 'pref-persist-sticky-group'
  | 'pref-tag-prefix-label'
  | 'pref-tag-type-automatic'
  | 'pref-tag-type-description'
  | 'pref-tag-type-label'
  | 'pref-tag-type-manual'
  | 'pref-template-html'
  | 'pref-template-label'
  | 'pref-template-markdown'
  | 'pref-title'
  | 'restore-grouping'
  | 'section-header'
  | 'ungrouped';
