// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "tagPrefix": string;
      "tagType": number;
      "navigateOnClick": boolean;
      "persistStickyGroup": boolean;
      "stickyGroups": string;
      "libraryColorRules": string;
      "itemColorRules": string;
      "templateId": string;
      "includeSubfolders": boolean;
      "includeUngrouped": boolean;
      "warningAcknowledged": boolean;
      "useCustomSelectionColor": boolean;
      "selectionColor": string;
    };
  }
}
